apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tf-overlays-remotestate
  description: Terraform remote state backend configuration (Azure Storage)
  annotations:
    github.com/project-slug: POps-Rox/tf-overlays-remotestate
    backstage.io/techdocs-ref: dir:.
  tags:
    - terraform
    - utility
    - platform-ops
  links:
    - url: https://github.com/POps-Rox/tf-overlays-remotestate
      title: GitHub Repository
      icon: github
spec:
  type: terraform-module
  owner: platform-ops-team
  lifecycle: production
  system: pops-rox-platform
